VVIT_IMAGE_SIZE = [
    1,
    18000,
]
VVIT_CHANNELS = 1
VVIT_PATCH_SIZE = [
    1,
    18,
]
VVIT_DIM = 256
VVIT_DEPTH = 4
VVIT_HEADS = 8
VVIT_NUM_CLASSES = 7
VVIT_MLP_DIM = 512
VVIT_POOL = "mean"
VVIT_DIM_HEAD = 64
VVIT_DROPOUT = 0.2
VVIT_EMB_DROPOUT = 0.1